### ISSUE TITLE
Pull together training corpus

### ISSUE THREAD

**Issue by fgregg** [dirko/pyhacrf#1]
> it might help to add quite a few dictionary words(~1000) with a single edit as matches and random pairs as mis-matches to give it a edit-distance-like starting point. 

I'll start working on this.

**Comment by fgregg** [comment]
Started this here: bb04b598663efe5644f9f1edd954a7b3699b6f07

**Comment by fgregg** [comment]
Per your suggestion, I gave pyharcrf training for about a thousand slight misspellings and then random pairs. It still can't tell if 'foo' and 'bar' are matches or not:

https://github.com/datamade/pyhacrf/blob/master/training.py

Any more suggestions?

**Comment by dirko** [comment]
Try adding the 'transition' feature:

```
# Extract features
feature_extractor = StringPairFeatureExtractor(match=True,
                                               numeric=True,
                                               transition=True)
```

and then it predicts

```
[[ 0.77647156  0.22352844]]
```

for 'foo' and 'bar' (I only used 100 examples instead of 1000 - maybe using all 1000 isn't necessary and you can get away with less).

The reason that it doesn't work without more features is that I forgot to add the bias term. Adding features works around this. 

I'll fix this bug by adding the bias term without regularization.

**Comment by dirko** [comment]
I added the bias term.
The original code now produce

```
[[ 0.82679638  0.17320362]]
```

for ('foo', 'bar') with 100 examples.
