### ISSUE TITLE
Levenshtein?

### ISSUE THREAD

**Issue by fgregg** [dirko/pyhacrf#28]
@dirko, could you explain what you mean here:

https://github.com/dirko/pyhacrf/blob/51455681d4edf88e5323313fc0f6b85577ae185c/pyhacrf/feature_extraction.py#L201

``` python
    def __init__(self, bias=1.0, start=False, end=False, match=False, numeric=False, transition=False):
        # TODO: For longer strings, tokenize and use Levenshtein
        # distance up until a lattice position.  Other (possibly)
        # useful features might be whether characters are consonant or
        # vowel, punctuation, case.
```

What do you mean by "use Levenshtein distance up until a lattice position"?

**Comment by dirko** [comment]
There are two things that I think might work after tokenisation:
- Add a new feature for position (i,j) that is the Levenshtein distance between seq1[0:i] and seq2[0:j].
- Add a new feature for position (i,j) that is the Levenshtein distance between seq1[i] and seq2[j].

For example, in the first case we have `"the rain in spain"` which is tokenised to `seq1=['the', 'rain', 'in', 'spain']`; and `"there in spain"` which is tokenised to `seq2=['there', 'in', 'spain']`.

Now in the first case the distance refers to these token distances, so the feature at `(i,j)=(0,0)` is 1 because `'the'!='there'` and `(i,j)=(1,1)` also is 1. The implied alignment is

```
'the'    'rain'  'in' 'spain'
'there'          'in' 'spain'
 SUB      DEL      -      -
```

(SUB=substitution, DEL=deletion, -=match)

In the second case, the distance is between the strings _within_ the sequence. So `(i,j)=(0,0)` implies the
distance between `'the'` and `'there'`. 

I think the second one makes a bit more sense since the CRF already does the alignment and 'distance'. 

The win here is that Levenshtein is much faster than the CRF, so we let the CRF do the overall alignment on `len(['the', 'rain', 'in', 'spain'])=4` elements instead of the detailed alignment on `len('the rain in spain')=17` elements. 

Another option might be a nested CRF where there is an outer, token-level, CRF and a inner, character-level, CRF. This shouldn't be faster than just using having one character-level model except if we can cache character-level results.

**Comment by fgregg** [comment]
Thanks for explaining this!
