### ISSUE TITLE
Latent classes?

### ISSUE THREAD

**Issue by fgregg** [dirko/pyhacrf#7]
General question.

The McAllum paper describes a model with multiple latent states but by default it seems that there are only two states (match, nonmatch)? Am I missing something?

**Comment by dirko** [comment]
Yes the default state machine in this implementation has only these two states. But by passing in more complicated state machines the same latent state effect as in the original paper can be implemented.

For example, by adding 

```
transitions = [
 (0, 0, (1, 1)),
 (1, 0, (1, 1)),
 (2, 0, (1, 1)),
 (0, 1, (0, 1)),
 (1, 1, (0, 1)),
 (2, 1, (0, 1)),
 (0, 2, (1, 0)),
 (1, 2, (1, 0)),
 (2, 2, (1, 0)),
... and then similar for the non-matching states
]
```

the latent three-state model is constructed.

The model that skips to end of the current word can be constructed by adding a function instead of a transition tuple:

```
def skipi(i, j, x):
    """ Skips over rows in the lattice until the next while-space 
        (feature number 13 equals 1 if white space) """
    for c in xrange(i, len(x[:, j])):
        if x[c, j, 13] == 1:
            return (c, j)

transitions = [
 (0, 1, skipi),
 ...
]
```

**Comment by fgregg** [comment]
Thanks for that!
